#!/bin/bash
docker run \
    --interactive \
    --rm \
    --user $(id -u):$(id -g) \
    --volume ~/.composer:/tmp \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $(pwd):/app \
    composer "$@"